architectblog/blog/urls.py
from django.urls import path
from .views import (
    IndexListView,
    EntryDetailView,
    EntryYearArchiveView,
    EntryMonthArchiveView,
    EntryDayArchiveView,
    EntrySearchView,
    TagArchiveView,
    LinkDetailView,
    QuoteDetailView,
    ArchiveView,
)

app_name = "blog"
urlpatterns = [
    path("", IndexListView.as_view(), name="home"),
    path(
        "<int:year>/<int:month>/<int:day>/<str:slug>/",
        EntryDetailView.as_view(month_format="%m"),
        name="entry_detail",
    ),
    path("<int:year>/", EntryYearArchiveView.as_view(), name="entry_archive_year"),
    path(
        "<int:year>/<int:month>/",
        EntryMonthArchiveView.as_view(month_format="%m"),
        name="entry_archive_month",
    ),
    path(
        "<int:year>/<int:month>/<int:day>/",
        EntryDayArchiveView.as_view(month_format="%m"),
        name="entry_archive_day",
    ),
    path("search/", EntrySearchView.as_view(), name="search"),
    path("tags/<tags>/", TagArchiveView.as_view(), name="tag_detail"),
    path(
        "links/<int:year>/<int:month>/<int:day>/<str:slug>/",
        LinkDetailView.as_view(month_format="%m"),
        name="link_detail",
    ),
    path(
        "quotes/<int:year>/<int:month>/<int:day>/<str:slug>/",
        QuoteDetailView.as_view(month_format="%m"),
        name="quote_detail",
    ),
    path("archive/", ArchiveView.as_view(), name="archive_view"),
]

architectblog/users/urls.py
from django.urls import path

from .views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("redirect/", view=user_redirect_view, name="redirect"),
    path("update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from filebrowser.sites import site
from architectblog.blog.views import HomeView

admin.autodiscover()

urlpatterns = [
    path("admin/filebrowser/", site.urls),
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("tinymce/", include("tinymce.urls")),
    path("", include("architectblog.blog.urls")),
    path("users/", include("architectblog.users.urls", namespace="users")),
    # path("", HomeView.as_view(), name="home"),
    path("pages/", include("django.contrib.flatpages.urls")),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

templates/_byline.html
<div class="fs-6">posted by {{ obj.author|capfirst }} &nbsp; <a
        href="/blog/{{ obj.created_time| date:"Y" }}/{{ obj.created_time| date:"m" }}/">{{ obj.created_time| date }}</a>
    <i class="bi bi-clock"></i><a href="{{ obj.get_absolute_url }}"> {{ obj.created_time| date:"P" }}</a></div>

templates/_footer.html
<br>
<br>
<br>
<footer class="footer mt-auto py-3 bg-light">
    <div class="container">
        <span class="text-muted">Architect mbcode</span>
    </div>
</footer>

templates/_pagination.html
{% if page.paginator.num_pages > 1 %} {% load blog_tags %}
    <nav>
        {% if page_total %}
            <strong>{{ page_total }} result{{ page_total|pluralize }} in {{ duration|floatformat:"2" }} seconds</strong>
            <hr>
        {% endif %}
        <ul class="pagination pagination-sm justify-content-center">
            {% if page.has_previous %}
                <li class="page-item"><a class="page-link" href="{% page_href 1 %}">&laquo;&laquo;</a></li>
                <li class="page-item"><a class="page-link" href="{% page_href page.previous_page_number %}">
                    {{ page.previous_page_number }}</a></li>
            {% endif %}
            <li class="page-item active"><a class="page-link"
                                            href="#"> {{ page.number }} of {{ page.paginator.num_pages }}</a></li>
            {% if page.has_next %}
                <li class="page-item"><a class="page-link"
                                         href="{% page_href page.next_page_number %}">{{ page.next_page_number }}</a>
                </li>
            {% endif %}
            {% if page.paginator.num_pages > 2 and page.number < page.paginator.num_pages %}
                <li class="page-item"><a class="page-link" href="{% page_href page.paginator.num_pages %}">&raquo;&raquo;</a>
                </li>
            {% endif %}
        </ul>
    </nav>
{% else %}
    {% if page_total %}
        <strong>{{ page_total }} result{{ page_total|pluralize }} in {{ duration|floatformat:"2" }} seconds</strong>
        <hr>
    {% endif %}
{% endif %}

templates/_tags.html
{% if obj.tags.count %}
    {% for tag in obj.tags.all %}
        <a class="btn btn-sm btn-secondary" href="{{ tag.get_absolute_url }}" rel="tag">

            {{ tag.tag }}
            <span class="badge bg-dark">{{ tag.total_count }}</span>
        </a>
    {% endfor %}
    <br>
    <br>
{% endif %}

templates/base.html
{% load static i18n %}
<!doctype html>
<html lang="en" class="h-100">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}Architect{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="A place for everything">
    <meta name="author" content="Matthew">

    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">

    {% block css %}
        <!-- CSS only -->
        <link href="{% static "custom.css" %}" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static "prism.css" %}">
        <link href="{% static "bootstrap-icons/font/bootstrap-icons.css" %}" rel="stylesheet">
        <!-- Your stuff: Third-party CSS libraries go here -->
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans&family=Roboto:ital,wght@0,300;1,900&display=swap"
              rel="stylesheet">
        <!-- Custom styles for this template -->
    {% endblock %}

    {% block javascript %}
        <!-- JavaScript Bundle with Popper -->
        <script src="{% static "bootstrap/dist/js/bootstrap.bundle.js" %}"></script>
    {% endblock javascript %}
    {% block extrahead %}
    {% endblock %}

</head>

<body class="d-flex flex-column h-100">
<nav class="navbar navbar-expand-lg navbar-light border-bottom mb-4 p-3" aria-label="navbarArchitect">
    <div class="container-lg">
        <a class="navbar-brand" href="{% url 'blog:home' %}">Architect</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarArchitect"
                aria-controls="navbarArchitect" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarArchitect">
            <ul class="navbar-nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a href="{% url 'blog:home' %}" class="nav-link px-2 link-dark">Home</a></li>
                {% if request.user.is_authenticated %}
                    <li><a href="{% url 'blog:home' %}"
                           class="nav-link px-2 link-dark">{% trans "Blog" %}</a>
                    </li>
                    <li><a href="https://wiki.mbcode.io"
                           class="nav-link px-2 link-dark">{% trans "Wiki" %}</a></li>
                {% else %}
                    <li class="nav-item"><a href="{% url 'blog:home' %}"
                                            class="nav-link px-2 link-dark">{% trans "Blog" %}</a></li>
                    <li class="nav-item"><a href="#" class="nav-link px-2 link-dark">Archive</a></li>
                {% endif %}
            </ul>
            <form class="col-12 col-sm-auto mb-3 mb-lg-0 me-lg-3" action="{% url 'blog:search' %}"
                  method="GET">
                <input type="search" class="form-control" placeholder="Search" name="q" value="{{ q }}">
            </form>
            <div class="dropdown text-end">
                <a href="{% static "user.png" %}" class="d-block link-dark text-decoration-none dropdown-toggle"
                   id="dropdownUser1"
                   data-bs-toggle="dropdown" aria-expanded="false">
                    <img src="{% static "user.png" %}" alt="user" width="32" height="32"
                         class="rounded-circle">
                </a>
                <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1" style="">
                    {% if not request.user.is_authenticated %}
                        <li><a class="dropdown-item"
                               href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
                        </li>
                        <li><a class="dropdown-item"
                               href="{% url 'account_login' %}">{% trans "Log In" %}</a></li>
                    {% endif %}
                    {% if request.user.is_authenticated %}
                        <li><a class="dropdown-item"
                               href="{% url 'users:detail' request.user.username %}">{% trans "Profile" %}</a>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item"
                               href="{% url 'account_change_password' %}">{% trans "Change Password" %}</a>
                        </li>
                        <li><a class="dropdown-item"
                               href="{% url 'account_logout' %}">{% trans "Log Out" %}</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</nav>


<div class="container text-decoration-none">

    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-dismissible fade show {% if message.tags %}alert-{{ message.tags }}{% endif %}"
                 role="alert">{{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
    {% endif %}

    {% block content %}
        <p>Standard template filler text</p>
    {% endblock content %}

</div> <!-- /container -->

{% block modal %}{% endblock modal %}

{% block inline_javascript %}
    {# Script tags with only code, no src (defer by default) #}
    <script src="{% static "prism.js" %}"></script>
{% endblock inline_javascript %}
</body>

{% include "_footer.html" %}

</html>

templates/base_2col.html
{% extends "base.html" %}

{% block bodyclass %}twocol{% endblock %}

{% block content %}
    <div class="row g-5">
        <div class="col-md-8">
            {% block main %}{% endblock %}
        </div>
        <div class="col-md-4">
            {% block sidebar %}{% endblock %}
        </div>
    </div>
{% endblock content %}